Controllers/CarrinhoCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteCore.Interfaces;
using LanchoneteCore.Models;
using LanchoneteCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchoneteCore.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IProdutoRepository produtoRepository, CarrinhoCompra carrinhoCompra)
        {
            _produtoRepository = produtoRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = Convert.ToDecimal(_carrinhoCompra.GetCarrinhoCompraTotal())
            };

            return View(carrinhoCompraVM);
        }
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int produtoID)
        {
            var produtoSelecionado = _produtoRepository.produtos.FirstOrDefault(p => p.ProdutoID == produtoID);

            if (produtoSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(produtoSelecionado, 1);
            }
            return RedirectToAction("Index");
        }
        public IActionResult RemoverItemDoCarrinhoCompra(int produtoID)
        {
            var produtoSelecionado = _produtoRepository.produtos.FirstOrDefault(p => p.ProdutoID == produtoID);
            if (produtoSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(produtoSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/FazerPedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteCore.Interfaces;
using LanchoneteCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace LanchoneteCore.Controllers
{
    public class FazerPedidoController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;

        public FazerPedidoController(IProdutoRepository produtoRepository)
        {
            _produtoRepository = produtoRepository;
        }


        public IActionResult List(string categoria)
        {
            ViewBag.Produto = "Produtos";
            var produtos = _produtoRepository.produtos;


            return View (produtos);
            //ViewBag.Categoria1 = "Categoria 1";
            //ViewData["Categoria2"] = "Categoria 2";

            //LancheListViewModel vm = new LancheListViewModel();
            //vm.Lanches = _lancheRepository.Lanches;
            //vm.CategoriaAtual = "Categoria do Lanche";

            //return View(vm);

            //string _categoria = categoria;
            /*
            IEnumerable<Produto> produtos;

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.LancheId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                if (string.Equals("Normal", _categoria, StringComparison.OrdinalIgnoreCase))
                    lanches = _lancheRepository.Lanches.Where(p => p.Categoria.CategoriaNome.Equals("Normal")).OrderBy(p => p.Nome);
                else
                    lanches = _lancheRepository.Lanches.Where(p => p.Categoria.CategoriaNome.Equals("Natural")).OrderBy(p => p.Nome);

                categoriaAtual = _categoria;
            }

            var lancheListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lancheListViewModel);
            */
        }
    }
}

Views/Shared/_FazerPedido.cshtml
@model LanchoneteCore.Models.Produto

    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <div class="caption">
                <h3 class="pull">@Model.Nome - R$@Model.ValorUnitario,00</h3>

                <div class="text-center view overlay hm-white-slight">
                    <img src="@Model.ImagemUrl" alt="ASP.NET" width="170" height="170" />
                    <a href="#">
                        <div class="mask waves-effect waves-light"></div>
                    </a>
                </div>
            </div>
            <div class="addToCart text-right">
                <p class="button ">
                    <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-produtoID="@Model.ProdutoID">
                        Incluir no Carrinho
                    </a>
                </p>
            </div>
            </div>
        </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lanchonete</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <partial name="_CookieConsentPartial" />

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2023 - Lanchonete</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>