Controllers/AtendentesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanchoneteCore.Models;

namespace LanchoneteCore.Controllers
{
    public class AtendentesController : Controller
    {
        private readonly LanchoneteCoreContext _context;

        public AtendentesController(LanchoneteCoreContext context)
        {
            _context = context;
        }

        // GET: Atendentes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Atendente.ToListAsync());
        }

        // GET: Atendentes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atendente = await _context.Atendente
                .FirstOrDefaultAsync(m => m.AtendenteID == id);
            if (atendente == null)
            {
                return NotFound();
            }

            return View(atendente);
        }

        // GET: Atendentes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Atendentes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AtendenteID,Nome,Telefone,Email")] Atendente atendente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(atendente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(atendente);
        }

        // GET: Atendentes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atendente = await _context.Atendente.FindAsync(id);
            if (atendente == null)
            {
                return NotFound();
            }
            return View(atendente);
        }

        // POST: Atendentes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AtendenteID,Nome,Telefone,Email")] Atendente atendente)
        {
            if (id != atendente.AtendenteID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(atendente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AtendenteExists(atendente.AtendenteID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(atendente);
        }

        // GET: Atendentes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var atendente = await _context.Atendente
                .FirstOrDefaultAsync(m => m.AtendenteID == id);
            if (atendente == null)
            {
                return NotFound();
            }

            return View(atendente);
        }

        // POST: Atendentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var atendente = await _context.Atendente.FindAsync(id);
            _context.Atendente.Remove(atendente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AtendenteExists(int id)
        {
            return _context.Atendente.Any(e => e.AtendenteID == id);
        }
    }
}

Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LanchoneteCore.Interfaces;
using LanchoneteCore.Models;
using LanchoneteCore.Services;

using LanchoneteCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchoneteCore.Controllers
{
        public class PedidoController : Controller
        {
            private readonly IPedidoRepository _pedidoRepository;
            private readonly CarrinhoCompra _carrinhoCompra;
            //private readonly PedidoService _pedidoService;

        public PedidoController(IPedidoRepository pedidoRepository, CarrinhoCompra carrinhoCompra)
            {
                _pedidoRepository = pedidoRepository;
                _carrinhoCompra = carrinhoCompra;
                //_pedidoService = pedidoService;
            }

            public IActionResult Checkout()
            {
                return View();
            }

            [HttpPost]
            public IActionResult Checkout(Pedido pedido)
            {
                var items = _carrinhoCompra.GetCarrinhoCompraItens();

                _carrinhoCompra.CarrinhoCompraItens = items;

                if (_carrinhoCompra.CarrinhoCompraItens.Count == 0)
                {
                    ModelState.AddModelError("", "Seu carrinho esta vazio, que tal incluir um lanche...");
                }

                if (ModelState.IsValid)
                {
                    _pedidoRepository.CriarPedido(pedido);
                    _carrinhoCompra.LimparCarrinho();
                    return RedirectToAction("CheckoutCompleto");
                }

                return View(pedido);
            }

            public IActionResult CheckoutCompleto()
            {
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido :) ";
                //return View();
                  return RedirectToAction("Create", "Clientes");
        }

        // GET: Pedidoes

    }
    }

Controllers/PedidoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanchoneteCore.Models;

namespace LanchoneteCore.Controllers
{
    public class PedidoesController : Controller
    {
        private readonly LanchoneteCoreContext _context;

        public PedidoesController(LanchoneteCoreContext context)
        {
            _context = context;
        }

        // GET: Pedidoes
        public async Task<IActionResult> Index()
        {
            var lanchoneteCoreContext = _context.Pedido.Include(p => p.Atendente).Include(p => p.Cliente);
            return View(await lanchoneteCoreContext.ToListAsync());
        }

        // GET: Pedidoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido
                .Include(p => p.Atendente)
                .Include(p => p.Cliente)
                .FirstOrDefaultAsync(m => m.PedidoID == id);
            
            if (pedido == null)
            {
                return NotFound();
            }
            int x = (int)id;
            TempData["valor"] = x;

            return RedirectToAction("Index", "PedidoDetalhes");
        }

        // GET: Pedidoes/Create
        public IActionResult Create()
        {
            ViewData["AtendenteID"] = new SelectList(_context.Atendente, "AtendenteID", "Nome");
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nome");
            return View();
        }

        // POST: Pedidoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PedidoID,Data,Hora,Statusp,ValorAtual,AtendenteID,ClienteID")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AtendenteID"] = new SelectList(_context.Atendente, "AtendenteID", "Nome", pedido.AtendenteID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nome", pedido.ClienteID);
            return View(pedido);
        }

        // GET: Pedidoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            ViewData["AtendenteID"] = new SelectList(_context.Atendente, "AtendenteID", "Nome", pedido.AtendenteID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nome", pedido.ClienteID);
            return View(pedido);
        }

        // POST: Pedidoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PedidoID,Data,Hora,Statusp,ValorAtual,AtendenteID,ClienteID")] Pedido pedido)
        {
            if (id != pedido.PedidoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.PedidoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AtendenteID"] = new SelectList(_context.Atendente, "AtendenteID", "Nome", pedido.AtendenteID);
            ViewData["ClienteID"] = new SelectList(_context.Cliente, "ClienteID", "Nome", pedido.ClienteID);
            return View(pedido);
        }

        // GET: Pedidoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedido
                .Include(p => p.Atendente)
                .Include(p => p.Cliente)
                .FirstOrDefaultAsync(m => m.PedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedidoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedido.FindAsync(id);
            _context.Pedido.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedido.Any(e => e.PedidoID == id);
        }
    }
}

Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LanchoneteCore.Models;
using LanchoneteCore.Services;
using LanchoneteCore.Interfaces;

namespace LanchoneteCore.Controllers
{
    public class ProdutoesController : Controller
    {
        private readonly LanchoneteCoreContext _context;

        public ProdutoesController(LanchoneteCoreContext context)
        {
            _context = context;
        }

        // GET: Produtoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Produto.ToListAsync());
        }

        // GET: Produtoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto
                .FirstOrDefaultAsync(m => m.ProdutoID == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        private void PopulateProdutoStatistics() {
            ViewBag.TotalProdutos = _context.Produto.Count();
            ViewBag.TotalDisponiveis = _context.Produto.Count(p => p.Disponibilidade == true);
            ViewBag.TotalIndisponiveis = _context.Produto.Count(p => p.Disponibilidade == false);
        }

        // GET: Produtoes/Create
        public IActionResult Create() {
            PopulateProdutoStatistics(); // Populando a ViewBag com informações reais
            return View();
        }


        // POST: Produtoes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProdutoID,Nome,Disponibilidade,ValorUnitario,ImagemUrl")] Produto produto) {
            if (ModelState.IsValid) {
                _context.Add(produto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create)); // Redirecionar para garantir que as informações da ViewBag sejam atualizadas
            }
            PopulateProdutoStatistics(); // Populando a ViewBag novamente em caso de erro de validação
            return View(produto);
        }

        // GET: Produtoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto.FindAsync(id);
            if (produto == null)
            {
                return NotFound();
            }
            return View(produto);
        }

        // POST: Produtoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProdutoID,Nome,Disponibilidade,ValorUnitario,ImagemUrl")] Produto produto)
        {
            if (id != produto.ProdutoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoExists(produto.ProdutoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produto);
        }

        // GET: Produtoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produto
                .FirstOrDefaultAsync(m => m.ProdutoID == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        // POST: Produtoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produto = await _context.Produto.FindAsync(id);
            _context.Produto.Remove(produto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoExists(int id)
        {
            return _context.Produto.Any(e => e.ProdutoID == id);
        }

       
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Painel da Lanchonete";
}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>Painel ERP Lanchonete</title>
    <style>
        /* CSS adicional para expandir a tela */
        html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            display: flex;
            height: 100%;
            overflow: hidden;
        }

        #sidebar-wrapper {
            flex: 0 0 250px;
        }

        #page-content-wrapper {
            flex-grow: 1;
            overflow-y: auto;
            padding: 20px;
        }

        /* Ajustes de Estilo - Textos e Elementos Visuais */
        .sidebar-heading {
            font-size: 1.8rem;
            padding: 1.5rem;
        }

        .list-group-item {
            font-size: 1.2rem;
            padding: 15px 20px;
        }

        .container-fluid {
            font-size: 1.1rem;
        }

        h1 {
            font-size: 2.5rem;
            margin-bottom: 1rem;
        }

        p.lead {
            font-size: 1.5rem;
            margin-bottom: 2rem;
        }

        .card {
            border-radius: 15px;
            transition: transform 0.3s, box-shadow 0.3s;
        }

            .card:hover {
                transform: scale(1.05);
                box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            }

        .card-title {
            font-size: 1.8rem;
        }

        .card-text {
            font-size: 1.2rem;
        }

        .btn {
            font-size: 1.2rem;
            padding: 10px 20px;
        }
    </style>
</head>
<body>
    <div id="wrapper">
        <!-- Menu Lateral -->
        <div id="sidebar-wrapper" class="bg-dark">
            <div class="sidebar-heading text-center py-4 text-white"><strong>Menu Principal</strong></div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index", "Pedidoes")" class="list-group-item list-group-item-action bg-dark text-white">Pedidos</a>
                <a href="@Url.Action("Index", "Produtoes")" class="list-group-item list-group-item-action bg-dark text-white">Produtos</a>
                <a href="@Url.Action("Index", "Atendentes")" class="list-group-item list-group-item-action bg-dark text-white">Estoque</a>
                <a href="@Url.Action("Create", "Clientes")" class="list-group-item list-group-item-action bg-dark text-white">Clientes</a>
                <a href="@Url.Action("Index", "Configuracoes")" class="list-group-item list-group-item-action bg-dark text-white">Configurações</a>
                <a href="@Url.Action("Logout", "Home")" class="list-group-item list-group-item-action bg-dark text-white">Sair</a>
            </div>
        </div>

        <!-- Conteúdo Principal -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <h1 class="mt-4">Bem-vindo ao ERP da Lanchonete</h1>
                <p class="lead">Gerencie seus pedidos, produtos e clientes de maneira fácil e intuitiva.</p>

                <!-- Cards de Atalhos Rápidos -->
                <div class="row">
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card text-white bg-success">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">Gerenciar Pedidos</h5>
                                <p class="card-text flex-grow-1">Acesse e controle todos os pedidos em andamento.</p>
                                <a href="@Url.Action("Index", "Pedido")" class="btn btn-light mt-auto">Acessar Pedidos</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card text-white bg-warning">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">Controle de Estoque</h5>
                                <p class="card-text flex-grow-1">Verifique e atualize o estoque dos produtos.</p>
                                <a href="@Url.Action("Index", "Estoque")" class="btn btn-light mt-auto">Ver Estoque</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card text-white bg-info">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">Relatórios</h5>
                                <p class="card-text flex-grow-1">Visualize os relatórios de vendas e performance.</p>
                                <a href="@Url.Action("Index", "Relatorios")" class="btn btn-light mt-auto">Ver Relatórios</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Views/Home/SanduicheResumo.cshtml
@model LanchoneteCore.Models.Produto

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.Nome" class="img-rounded" alt="@Model.Nome" width="225" height="225" />
        <div class="caption">
            <h3 class="pull-right">@Model.ValorUnitario.ToString("c")</h3>
            <h3>
                <a asp-controller="Lanche" asp-action="Details" asp-route-produtoID="@Model.ProdutoID">@Model.Nome</a>
            </h3>
            <p>@Model.Nome</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-produtoID="@Model.ProdutoID">
                    Incluir no Carrinho
                </a>
            </p>
        </div>
    </div>
</div>